### ISSUE TITLE
Please consider new CRAN submission to allow for next version of future to be released

### ISSUE THREAD

**Issue by HenrikBengtsson** [nt-williams/lmtp#101]
Hi again.  Bug #100 turns out to be a blocker prevent me from releasing the next version of **future** to CRAN.  (I actually already submitted to CRAN and they caught this during their own reverse-dependency checks.)

I'm only allowed to break reverse dependencies (here: your package) after having given you a reasonable chance to fix it, and I think reasonable chance by their terms means two weeks.  If you have time already now, could you please submit an updated version of **lmtp** to CRAN that fixes #100?

If you don't have time to submit before then, I'll wait two weeks to re-submit the next version of **future** with a note to the CRAN team.  If they accept my new version at that time, then your package will break immediately after and you'll probably get an email from CRAN asking you to fix it.

Details:

```
---------- Forwarded message ---------
From: <ligges - at - statistik -dot- tu-dortmund -dot- de>
Date: Thu, Aug 12, 2021 at 5:01 PM
Subject: [CRAN-pretest-waiting] CRAN submission future 1.22.1
To: <henrikb@braju.com>
Cc: <CRAN-submissions@r-project.org>


Dear maintainer,

package future_1.22.1.tar.gz has been auto-processed. The auto-check found problems
when checking the first order strong reverse dependencies.
Please reply-all and explain: Is this expected or do you need to fix anything in your package?
If expected, have all maintainers of affected packages been informed well in advance?
Are there false positives in our results?

*** Changes to worse in reverse dependencies ***
Debian: <https://win-builder.r-project.org/incoming_pretest/future_1.22.1_20210811_174431/reverseDependencies/summary.txt>
```
Thank you

**Comment by nt-williams** [comment]
Hi @HenrikBengtsson. Sorry this bug is holding up your CRAN submission! I'll work on releasing a minor patch today to resolve this. Thanks for identifying how to fix as well.

**Comment by HenrikBengtsson** [comment]
@nt-williams , that would be wonderful. This will allow me to ask the CRAN Team to hold on to future v1.22.1 that is currently pending and wait for an updated version of lmtp to come in first.  Thank you so much!

**Comment by nt-williams** [comment]
@HenrikBengtsson, v0.9.1 was accepted on CRAN this morning and the package source is now available. I tested this version against future v1.22.1 and could no loner produce the error. I hope this helps! BTW, thanks for making future, it's great to use and really speeds up lmtp!

**Comment by HenrikBengtsson** [comment]
Thank you. I just notice that too, and I've asked CRAN to move forward with future 1.22.1. Thanks for the kind words and thanks for the swift action here.
