### ISSUE TITLE
Reduntant if statement

### ISSUE THREAD

**Issue by lorenzoFabbri** [nt-williams/lmtp#126]
https://github.com/nt-williams/lmtp/blob/8ff28f82576d5bbc59225abd1b9d807d7a4ca9cb/R/lmtp_Task.R#L36

Isn't this `if else` statement the same as the `if` statement above?

**Comment by nt-williams** [comment]
It is redundant, but the verboseness of it is on purpose to enumerate all possibilities. Thanks for checking!
