### ISSUE TITLE
Weights not used in standard error calculation

### ISSUE THREAD

**Issue by kathoffman** [nt-williams/lmtp#134]
Hi @nt-williams, I believe the standard errors when weights are given are not currently incorporating the weights, see `theta.R`, line 94.

```
se <- sqrt(var(vapply(clusters, function(x) mean(x), 1)) / j)
```

https://github.com/nt-williams/lmtp/blob/master/R/theta.R#L94

**Comment by nt-williams** [comment]
Thanks! Fixed with commit 13faf4f
