### ISSUE TITLE
Why is `cumprod` not applied to density ratios in `cf_tmle2()` as in `cf_tmle()`

### ISSUE THREAD

**Issue by ddu10300** [nt-williams/lmtp#151]
Thank you very much for implementing the bootstrap method for TMLE using the modified TMLE algorithm https://arxiv.org/abs/1810.03030. I noticed that in the `cf_tmle2()` function, the density ratio is used directly as the weight, unlike in `cf_tmle()`, where it’s calculated using the cumulative product:
```
ratios <- matrix(t(apply(ratios, 1, cumprod)),
                 nrow = nrow(ratios),
                 ncol = ncol(ratios))
```
Since the algorithm described in the original paper uses the cumulative treatment probability, could you clarify the reasoning behind this difference? Why is `cumprod` not applied to the density ratios in `cf_tmle2()`? 

Thank you very much!

**Comment by nt-williams** [comment]
Thanks for pointing this out! It's been fixed in devel.
