### ISSUE TITLE
Allow user to pass non-quoted column names to trt, outcome, and baseline variables

### ISSUE THREAD

**Issue by hoffmakl** [nt-williams/lmtp#71]
If possible (without introducing a bunch of dplyr dependencies), it would be nice to change the trt, outcome and baseline args of the lmtp_sub/ipw/tmle/sdr estimators to allow quoted or non-quoted variable names to be passed through. If not possible, the help files should be changed so that it is clear that the column names need to be passed as character strings.

**Comment by nt-williams** [comment]
After some thought, I don't think this is a worthwhile enhancement. Passing arguments as character strings is standard and quasi-quotation is an exception.
