### ISSUE TITLE
Elaborate on error for lmtp_contrast

### ISSUE THREAD

**Issue by kathoffman** [nt-williams/lmtp#73]
Currently the error for `lmtp_contrast` when using `lmtp_sub` or `lmtp_ipw` objects is that `lmtp_contrast` is not implemented for these estimators. It may be helpful to elaborate that this is purposeful, since we do not have any asymptotic linearity theory to support SEs from these estimators when ensemble learning is used. Also, maybe an explicit recommendation that "the authors of lmtp recommend using the tmle or sdr estimation methods for optimal results" would be good? Perhaps a reference would be helpful, too. Right now I can only think of Sherri Rose's Intro to TMLE paper as a good ref for an approachable explanation of the cons of IPW/G comp, but there's probably other good ones! https://academic.oup.com/aje/article/185/1/65/2662306

**Comment by nt-williams** [comment]
@hoffmakl Want to tackle this?

**Comment by hoffmakl** [comment]
sounds like a dream
