### ISSUE TITLE
Add outcome_type = 'survival'

### ISSUE THREAD

**Issue by nt-williams** [nt-williams/lmtp#76]

**Comment by nt-williams** [comment]
Closed with PR #86

**Comment by yusukematsuyama** [comment]
Dear Dr. Williams,

I thought the lmtp_tmle(outcome_type = "survival") reports the proportion of survive (i.e., Y = 0) at the end of follow-up, rahter than the proportion of event (i.e., Y = 1). Am I understanding it correctly?
