### ISSUE TITLE
DESCRIPTION: Please add URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [nt-williams/lmtp#99]
Hi, please consider adding:

```
URL: https://github.com/nt-williams/lmtp
BugReports: https://github.com/nt-williams/lmtp/issues
```

to your package DESCRIPTION file to make it easier to find this repo, e.g. from https://cran.r-project.org/web/packages/lmtp/index.html.

**Comment by nt-williams** [comment]
Resolved in PR #102
